#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Takagi Issei
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = []

for line in sys.stdin:
    raw = line.rstrip("\n")
    text = raw.strip()


